name: Deploy to Dokku - production

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get env-var
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo ${{ GITHUB_SHA }}
