name: Deploy to Dokku - production

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Dokku deploy
        uses: devb15/dokku-github-action@v1.0
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          HOST: apps.mobird.in
          PROJECT: mynewapp
          CONFIG: ${{ secrets.APP_CONFIG }}
          BRANCH: "test"
